# Simulation
SIM_DURATION = 600
BUOYS_COUNT = 50
IDEAL_CHANNEL = 1

# World
WORLD_WIDTH = 600.0
WORLD_HEIGHT = 600.0

# Buoys
MOBILE_BUOY_PERC = 0.10
DEFAULT_BUOY_VELOCITY = 15.0
NEIGHBOR_TIMEOUT = 15.0

# Network
BIT_RATE = 1000000
SPEED_OF_LIGHT = 300000000.0
COMM_RANGE_MAX = 120.0
COMM_RANGE_HIGH_PROB = 70.0
DELIVERY_PROB_HIGH = 0.90
DELIVERY_PROB_LOW = 0.15

# CSMA
DIFS_TIME = 2.0e-05
SLOT_TIME = 5.0e-05
CW = 16

# Scheduler
SCHEDULER_MODE = "Static"
BEACON_MIN_INTERVAL = 1.0
BEACON_MAX_INTERVAL = 5.0
BEACON_STATIC_INTERVAL = 5.0
NEIGHBORS_THRESHOLD = 15
CONTACT_THRESHOLD = 20.0
